// STUB FILE -- regenerated by `npm run types` (runs `now-sdk dependencies`).
// Holds the ambient globals available to legacy inline client scripts
// (`*.client.js`) referenced from Fluent metadata.
// Do not add hand-written declarations here; they will be overwritten.
